#!/bin/bash
. /var/openpanel/api/sh/module.sh

WordpressAdmin.update() {
  appid=wordpress
  newpass=$(coreval WordpressAdmin password)
  MD5_PWD=$(echo -n ${newpass} | md5sum | cut -f 1 -d ' ')
  authd runscript openapp-call "$appid" passwd "MD5|$MD5_PWD"

  siteurl=$(coreval WordpressAdmin site_url)
  authd runscript openapp-call "$appid" siteurl "$siteurl"
}

Module.getconfig() {
  cat << _EOF_
  <openpanel.module>
    <dict id="WordpressAdmin" type="class">
      <dict id="Admin">
	    <string id="password">*</string>
      </dict>
    </dict>
  </openpanel.module>
_EOF_
  exitquiet
}

implement OpenAppWordpress.module
